<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Modèle linéaire généralisé : les pruniers</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 54px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 59px;
  margin-top: -59px;
}

.section h2 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h3 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h4 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h5 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h6 {
  padding-top: 59px;
  margin-top: -59px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Modèle linéaire pour l'écologie</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Organisation</a>
</li>
<li>
  <a href="https://github.com/MarieEtienne/coursml">
    <span class="fa fa-github"></span>
     
    dépôt github
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-child"></span>
     
    Introduction à R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intror_presentation.html">Présentation du logiciel R</a>
    </li>
    <li>
      <a href="intror_rstudio.html">Environnement RStudio</a>
    </li>
    <li>
      <a href="intror_manip.html">Manipulation de données</a>
    </li>
    <li>
      <a href="intror_visu.html">Visualisation</a>
    </li>
    <li>
      <a href="intror_rappel.html">Rappels de statistique</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-adjust"></span>
     
    Echantillonnage
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="echant_variabilite.html">Statistique inférentielle, généralités</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-tilde"></span>
     
    Modèle linéaire
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="anova2.html">Anova</a>
    </li>
    <li>
      <a href="regression.html">Regression</a>
    </li>
    <li>
      <a href="ancova.html">Analyse de la covariance</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Modèle linéaire généralisé : les pruniers</h1>

</div>


<div id="presentation" class="section level1">
<h1>Présentation</h1>
<p>Nous cherchons à mesurer l’effet de la taille (influence de la longueur des racines et la date de replantation) sur la survie de plans de pruniers. Pour chacun des 4 traitements (Date * Longueur), les pruniers vivants et morts sont comptés.</p>
<p>D’un point de vue opérationnel dans , on veut d’abord réorganiser les données pour avoir une observation par lignes :</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prune &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/Prune.txt&quot;</span>,<span class="dt">header=</span>T)
prune</code></pre></div>
<pre><code>##   Longueur      Date   Etat Effectif
## 1    court   automne vivant      156
## 2    court   automne   mort       84
## 3    court printemps vivant       84
## 4    court printemps   mort      156
## 5     long   automne vivant      107
## 6     long   automne   mort      133
## 7     long printemps vivant       31
## 8     long printemps   mort      209</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prune &lt;-<span class="st"> </span>prune <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(<span class="dt">key =</span> Etat, <span class="dt">value =</span> Effectif) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">total =</span> mort <span class="op">+</span><span class="st"> </span>vivant)</code></pre></div>
<p>On peut ensuite regarder, les probabilités de survie empiriques sur nos données :</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prune <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">SurvieEmpir =</span> vivant<span class="op">/</span>total)</code></pre></div>
<pre><code>##   Longueur      Date mort vivant total SurvieEmpir
## 1    court   automne   84    156   240   0.6500000
## 2    court printemps  156     84   240   0.3500000
## 3     long   automne  133    107   240   0.4458333
## 4     long printemps  209     31   240   0.1291667</code></pre>
<p>Il semble effectivement, qu’il y ait une différence de survie entre les différentes observations.</p>
</div>
<div id="modele-logistique-sur-la-longueur" class="section level1">
<h1>Modèle logistique sur la longueur</h1>
<p>On souhaite savoir si la longueur a une influence sur la survie des plans de pruniers.</p>
<p>Pour celà, on définit le modèle</p>
<p><span class="math display">\[\mbox{M1} \left \lbrace \begin{array}{rl} 
    Y_{ij} &amp; \overset{ind}{\sim}\mathcal{B}(n_{ij}, p_{i} ) \\
    logit(p_{i})&amp;=\mu +\alpha_i
  \end{array} \right.
\]</span></p>
<p>Ce moèle n’est pas identifiable, on doit ajouter une contrainte. La contrainte utilisée par  est <span class="math inline">\(\alpha_1=0\)</span>.</p>
<p>&lt;&lt;&gt;&gt;= @</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">glm1 &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(vivant,mort)<span class="op">~</span>Longueur, <span class="dt">family=</span><span class="kw">binomial</span>(logit), <span class="dt">data=</span>prune)
<span class="kw">summary</span>(glm1)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(vivant, mort) ~ Longueur, family = binomial(logit), 
##     data = prune)
## 
## Deviance Residuals: 
##      1       2       3       4  
##  4.684  -4.684   5.200  -5.854  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   6.011e-17  9.129e-02   0.000        1    
## Longueurlong -9.076e-01  1.360e-01  -6.672 2.53e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 151.02  on 3  degrees of freedom
## Residual deviance: 105.18  on 2  degrees of freedom
## AIC: 131.92
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Les tests présentés dans la commande summary, sont les tests portant sur la nullité des paramètres et utilisent la normalité asymptotique des estimateurs du maximum de vraisemblance. Ici on voit que la statistique est notée  sur la troisième colonne, ce qui correspond à un test où la variance asymptotique des estimateurs est connue (sinon on aurait un test de student).</p>
<p>On peut tester le modèle M1 contre le modèle M0, pour tester l’existence d’un effet de la longueur de coupe sur la survie. M0 désigne le modèle nul :</p>
<p><span class="math display">\[\mbox{M0} \left \lbrace \begin{array}{rl} 
    Y_{ij} &amp; \overset{ind}{\sim}\mathcal{B}(n_{ij}, p ) \\
    logit(p_{i})&amp;=\mu 
  \end{array} \right.
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(glm1, <span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: cbind(vivant, mort)
## 
## Terms added sequentially (first to last)
## 
## 
##          Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                         3     151.02              
## Longueur  1   45.837         2     105.18 1.285e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Ici la déviance expliquée par le passage du modèle M0 au modèle M1 vaut 45.8. Sous l’hypothèse H0 : ``les deux modèles M0 et M1 sont équivalents’’, cette statistique suit une loi du Chi 2 à 1 degré de liberté. La probabilité critique associé à ce test vaut <span class="math inline">\(1.285e-11\)</span>, on rejette donc H0. La déviance résiduelle vaut 105.18, c’est la déviance qui reste inexpliquée par le modèle.</p>
</div>
<div id="modele-logistique-sur-la-longueur-et-date" class="section level1">
<h1>Modèle logistique sur la longueur et date</h1>
<p>On souhaite savoir si la date ou la longueur de coupe ont un effet sur la survie des plans de pruniers.</p>
<p>Pour cela, on pose le modèle</p>
<p><span class="math display">\[\mbox{Mint} \left \lbrace \begin{array}{rl} 
    Y_{ij} &amp; \overset{ind}{\sim}\mathcal{B}(n_{ij}, p_{ij} ) \\
    logit(p_{i})&amp;=\mu +\alpha_i+\beta_j+\gamma_{ij}
  \end{array} \right.
\]</span></p>
<p>Dans , on utilise les commandes suivantes pour estimer les paramètres du modèle.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">glmint &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(vivant,mort)<span class="op">~</span>Date<span class="op">+</span>Longueur<span class="op">+</span>Longueur<span class="op">*</span>Date, <span class="dt">family=</span><span class="kw">binomial</span>(logit), <span class="dt">data=</span>prune)
<span class="kw">summary</span>(glmint)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(vivant, mort) ~ Date + Longueur + Longueur * 
##     Date, family = binomial(logit), data = prune)
## 
## Deviance Residuals: 
## [1]  0  0  0  0
## 
## Coefficients:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                  0.6190     0.1353   4.574 4.78e-06 ***
## Dateprintemps               -1.2381     0.1914  -6.469 9.87e-11 ***
## Longueurlong                -0.8366     0.1876  -4.460 8.19e-06 ***
## Dateprintemps:Longueurlong  -0.4527     0.3009  -1.505    0.132    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1.5102e+02  on 3  degrees of freedom
## Residual deviance: 1.1191e-13  on 0  degrees of freedom
## AIC: 30.742
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(glmint, <span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: cbind(vivant, mort)
## 
## Terms added sequentially (first to last)
## 
## 
##               Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                              3    151.019              
## Date           1   97.579         2     53.440 &lt; 2.2e-16 ***
## Longueur       1   51.147         1      2.294 8.572e-13 ***
## Date:Longueur  1    2.294         0      0.000    0.1299    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Anova</span>(glmint, <span class="dt">test=</span><span class="st">&quot;LR&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: cbind(vivant, mort)
##               LR Chisq Df Pr(&gt;Chisq)    
## Date           102.889  1  &lt; 2.2e-16 ***
## Longueur        51.147  1  8.572e-13 ***
## Date:Longueur    2.294  1     0.1299    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La commande  donne les tests de type I, tandis que la commande  donne les tests de type II.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
